spring.application.name=ecommerce-platform

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT Configuration
jwt.secret=MySuperSecretKeyForJwtAuthentication2026MySuperSecretKey
jwt.expiration=86400000

# Razorpay Configuration
razorpay.key.id=test_key
razorpay.key.secret=test_secret

# Email Configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=bantusupriya8@gmail.com
spring.mail.password=wwqr dihd mved tvtp


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Cloudinary Configuration

cloudinary.cloud-name=rta2lgab
cloudinary.api-key=656723683396819
cloudinary.api-secret=N3fNWY6SUq6wkfs87j_nx8G-pak

# File Upload Configuration
spring.servlet.multipart.enabled=true

# Maximum file size
spring.servlet.multipart.max-file-size=10MB

# Maximum request size
spring.servlet.multipart.max-request-size=10MB